/**
 * Database TypeScript Types
 * 
 * Shared type definitions for database entities. These types provide compile-time
 * safety for lottery enums, status fields, and JSONB structures.
 * 
 * Usage:
 * ```typescript
 * import { Lottery, SuggestionStatus, Game, PrizeTiers } from '@/types/database';
 * 
 * const lottery: Lottery = 'megasena';
 * const game: Game = { numbers: [3, 12, 18, 27, 34, 45] };
 * ```
 * 
 * Note: Drizzle automatically infers table types. Import table schemas directly
 * for type-safe queries:
 * ```typescript
 * import { users, suggestions } from '@/lib/db/schema';
 * 
 * type User = typeof users.$inferSelect; // Inferred from schema
 * type NewUser = typeof users.$inferInsert; // For inserts
 * ```
 */

// Lottery Types
export type Lottery = 'megasena' | 'lotofacil';

// Suggestion Status Enum
export type SuggestionStatus = 'pending' | 'realized' | 'verified';

// Prize Tier Types (different tiers for different lotteries)
export type PrizeTierMega = 'sena' | 'quina' | 'quadra' | 'terno';
export type PrizeTierLotofacil = 'quinze' | 'quatorze' | 'treze' | 'doze' | 'onze';
export type PrizeTier = PrizeTierMega | PrizeTierLotofacil;

/**
 * Game Structure (stored in suggestions.games JSONB field)
 * 
 * Each suggestion contains an array of games generated by the wheeling engine.
 * Each game is a set of lottery numbers.
 * 
 * Example for Mega Sena:
 * ```json
 * [
 *   { "numbers": [3, 12, 18, 27, 34, 45] },
 *   { "numbers": [5, 15, 22, 31, 38, 50] }
 * ]
 * ```
 */
export interface Game {
  numbers: number[]; // Array of lottery numbers (6 for Mega, 15-20 for Lotofácil)
}

/**
 * Prize Tiers Structure (stored in lottery_results.prizes JSONB field)
 * 
 * Prize values for each tier, stored in centavos (integer).
 * Different lotteries have different prize tiers (all fields optional).
 * 
 * Example for Mega Sena:
 * ```json
 * {
 *   "sena": 5000000,     // R$ 50,000.00 in centavos
 *   "quina": 50000,      // R$ 500.00
 *   "quadra": 10000      // R$ 100.00
 * }
 * ```
 */
export interface PrizeTiers {
  // Mega Sena prize tiers
  sena?: number;    // 6 numbers matched - R$ value in centavos
  quina?: number;   // 5 numbers matched
  quadra?: number;  // 4 numbers matched
  terno?: number;   // 3 numbers matched (rare, usually only quina paga)

  // Lotofácil prize tiers
  quinze?: number;     // 15 numbers matched - R$ value in centavos
  quatorze?: number;   // 14 numbers matched
  treze?: number;      // 13 numbers matched
  doze?: number;       // 12 numbers matched
  onze?: number;       // 11 numbers matched
}

// Re-export Drizzle inferred types for convenience
// Note: These will be available once schema is imported in consuming code
export type { users, suggestions, lotteryResults, prizes } from '@/lib/db/schema';
